# This file was generated by GoReleaser. DO NOT EDIT.
cask "slow" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "3f06bfc8cffdaa970aea373f02c6cb66b65e4c3ced05253e565eb4f6a102b25f"
      url "https://github.com/GabeSoler/slow/releases/download/v#{version}/slow_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6eceb1c953e5760bf7c87a7ca46da0ea426308037dbd59c234e428de8b952c4d"
      url "https://github.com/GabeSoler/slow/releases/download/v#{version}/slow_Darwin_arm64.tar.gz"
    end
  end

  name "slow"
  desc "Slow is an app that cares for your mental health as a programmer"
  homepage "https://github.com/gabrielsoler/slow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slow"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{caskroom_path}/#{version}/slow"]
  end

  # No zap stanza required

end
