# This file was generated by GoReleaser. DO NOT EDIT.
cask "slow" do
  version "0.1.13"

  on_macos do
    on_intel do
      sha256 "c5a53e983fd95760c7421a5a02e8feff73dbf17df3042b314c5f423516cd392d"
      url "https://github.com/GabeSoler/slow/releases/download/v#{version}/slow_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4304cfae04841d962824e411c49f0a4ddd0f79a6edf7795aa9e47b4cd17daabe"
      url "https://github.com/GabeSoler/slow/releases/download/v#{version}/slow_Darwin_arm64.tar.gz"
    end
  end

  name "slow"
  desc "Slow is an app that cares for your mental health as a programmer"
  homepage "https://github.com/gabrielsoler/slow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slow"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{caskroom_path}/#{version}/slow"]
  end

  # No zap stanza required

end
