# This file was generated by GoReleaser. DO NOT EDIT.
cask "slow" do
  version "0.1.7"

  on_macos do
    on_intel do
      sha256 "68f0d3a28cf6ea4b5d2d36800bce12cff8d8b88d21a0f38b937d6e4c8ba827d7"
      url "https://github.com/GabeSoler/slow/releases/download/v#{version}/slow_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "174037471a24ee80b7057e3c49f83c0e6cdf0e4180576d66f3f448620f656071"
      url "https://github.com/GabeSoler/slow/releases/download/v#{version}/slow_Darwin_arm64.tar.gz"
    end
  end

  name "slow"
  desc "Slow is an app that cares for your mental health as a programmer"
  homepage "https://github.com/gabrielsoler/slow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slow"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slow"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This application is designed specifically to run on macOS systems.
  EOS
end
