# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slow < Formula
  desc "Slow is an app that cares for your mental health as a programmer"
  homepage "https://github.com/gabrielsoler/slow"
  version "0.1.6"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/GabeSoler/slow/releases/download/v0.1.6/slow_Darwin_x86_64.tar.gz"
    sha256 "a4417b8e043acc130a4c313283603dd7099bbd2c069d1542109a30d90692ee43"

    define_method(:install) do
      bin.install "slow"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/GabeSoler/slow/releases/download/v0.1.6/slow_Darwin_arm64.tar.gz"
    sha256 "fccd906ac6ea41ef5dd11492574b6c2c009b37dd57b0a2c09ab169c22bcd54a8"

    define_method(:install) do
      bin.install "slow"
    end
  end

  def caveats
    <<~EOS
      This application is designed specifically to run on macOS systems.
    EOS
  end
end
